apiVersion: v1
kind: Service
metadata:
  labels:
    app: ols-controller-app
  name: ols-controller-svc
spec:
  ports:
  - name: cli
    nodePort: 31052
    port: 8101
    targetPort: 8101
  - name: rest
    nodePort: 30052
    port: 8181
    targetPort: 8181
  selector:
    app: ols-controller-app
  type: NodePort